- name: Deploy Docker Container on App Node
  hosts: app
  become: true
  tasks:
    - name: Stop existing container
      shell: docker ps -q --filter "ancestor=vipinms90/finance-me:1.0" | xargs -r docker stop

    - name: Remove stopped container
      shell: docker ps -a -q --filter "ancestor=vipinms90/finance-me:1.0" | xargs -r docker rm

    - name: Pull Docker image
      shell: docker pull vipinms90/finance-me:1.0

    - name: Run Docker container
      shell: docker run -d -p 8081:8081 vipinms90/finance-me:1.0
